#!/bin/bash

#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=300g
#SBATCH --time=48:00:00
#SBATCH --job-name=pass_annotation
#SBATCH --output=/share/BioinfMSc/Bill_resources/Tbrucei/fastq/Group2/bashoutput/slurm-%x-%j.out
#SBATCH --error=/share/BioinfMSc/Bill_resources/Tbrucei/fastq/Group2/bashoutput/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mbxzy2@nottingham.ac.uk

source $HOME/.bash_profile

conda activate rnasequence

for i in $(ls -l CSF*.fastq.gz)
do
trim_galore -q 28 --length 40 -o CSF_trimmed $i
done

conda deactivate
