#!/bin/bash

#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=100g
#SBATCH --time=06:00:00
#SBATCH --job-name=htseq_csf
#SBATCH --output=/share/BioinfMSc/Bill_resources/Tbrucei/fastq/Group2/bashoutput/slurm-%x-%j.out
#SBATCH --error=/share/BioinfMSc/Bill_resources/Tbrucei/fastq/Group2/bashoutput/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mbxzy2@nottingham.ac.uk

source $HOME/.bash_profile

conda activate htseq

python -m HTSeq.scripts.count -a 10 -t exon CSF1trimmed.sam TriTrypDB-68_TbruceiTREU927.gff > CSF1_htseq.txt

python -m HTSeq.scripts.count -a 10 -t exon CSF2trimmed.sam TriTrypDB-68_TbruceiTREU927.gff > CSF2_htseq.txt

python -m HTSeq.scripts.count -a 10 -t exon CSF3trimmed.sam TriTrypDB-68_TbruceiTREU927.gff > CSF3_htseq.txt

python -m HTSeq.scripts.count -a 10 -t exon CSF4trimmed.sam TriTrypDB-68_TbruceiTREU927.gff > CSF4_htseq.txt

conda deactivate
